# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
# fos_elastica:
#     clients:
#         default: { url: '%env(ELASTICSEARCH_URL)%' }
#         #default: { host: localhost, port: 9200 }
#     indexes:        
#         app:
#             types:
#                 dossier:
#                     properties:
#                         cote: ~
#                         titre: ~
#                         analyse: ~
#                     persistence:
#                         # the driver can be orm, mongodb or phpcr
#                         driver: orm
#                         model: App\Entity\Dossier
#                         provider: ~
#                         finder: ~
        #app: null
        #app: ~

